// vue/vue-music/vue_music/src/components/searchBox.vue
<template>
  <div class="search-box">
    <!-- <i class="icon-search"></i> -->
     <input :placeholder="placeholder" @keyup.enter="search" v-model="query" type="text" class="box">
    
    <!-- <img @click="search" class="search_img" src="../assets/search.png" alt=""> -->
    <!-- <span class="search" >{{clickInfo}}</span> -->
  </div>
</template>

<script>
// import { emit } from 'cluster'
// import {debounce} from 'common/js/utl'
export default {
  props: {
    placeholder: {
      type: String,
      default: '搜索歌曲、歌手'
    }
  },
  data () {
    return {
      query: '',
      clickInfo: '搜索'
    }
  },
  methods: {
    clear () {
      this.query = ''
    },
    search(){
        this.$emit('search',this.query)
    },
    setQuery () {
      console.log(this.query)
    }
  }
}
</script>

<style scoped lang="stylus">
.search-box {
//   position: relative;
  display: flex;
  align-items: center;
  box-sizing: border-box;
  width: 90%;
//   margin-left 2%
//   margin-top 20px;
  height: 40px;
  border-bottom: 1px solid rgb(235, 235, 235);
  background-color #d44439
  
  .search_img{
    width 25px
    height 25px
    margin 0
    padding 0
  }
  .box {
    flex: 1;
    line-height: 25px;
    // width 699px
    background: rgb(212, 68, 57);
    color: #fff;
    font-size:14px;
    border: none;
    outline: medium;
    &::placeholder {
      color: rgba(255, 255, 255, 0.6);
    }
  }
  .icon-delete {
    position: absolute;
    right: 12px;
    font-size: 14px;
    color: rgba(255, 255, 255, 0.8);
    border: none;
  }
  .search {
    padding: 0 5px;
    font-size: 14px;
    color:#2E3030;
  }
}
</style>

// react/react-music/src/baseUI/search-box/index.js
import React, {useRef, useState, useEffect, useMemo} from 'react';
import styled from 'styled-components';
import style from '../../assets/global-style';
import { debounce } from './../../api/utils';

const SearchBoxWrapper = styled.div`
  display: flex;
  align-items: center;
  box-sizing: border-box;
  width: 100%;
  padding: 0 6px;
  padding-right: 20px;
  height: 40px;
  background: ${style["theme-color"]};
  .icon-back{
    font-size: 24px;
    color: ${style["font-color-light"]};
  }
  .box{
    flex: 1;
    margin: 0 5px;
    line-height: 18px;
    background: ${style["theme-color"]};
    color: ${style["highlight-background-color"]};
    font-size: ${style["font-size-m"]};
    outline: none;
    border: none;
    border-bottom: 1px solid ${style["border-color"]};
    &::placeholder{
      color: ${style["font-color-light"]};
    }
  }
  .icon-delete{
    font-size: 16px;
    color: ${style["background-color"]};
  }
`

const SearchBox = (props) => {
  const queryRef = useRef();
  const [query, setQuery] = useState('');

  const { newQuery } = props;
  const { handleQuery } = props;

  let handleQueryDebounce = useMemo(() => {
    return debounce(handleQuery, 500);
  }, [handleQuery]);

  useEffect(() => {
    queryRef.current.focus();
  }, []);

  useEffect(() => {
    handleQueryDebounce(query);
    // eslint-disable-next-line 
  }, [query]);

  useEffect(() => {
    let curQuery = query;
    if(newQuery !== query){
      curQuery = newQuery;
      queryRef.current.value = newQuery;
    }
    setQuery(curQuery);
    // eslint-disable-next-line
  }, [newQuery]);

  const handleChange = (e) => {
    let val = e.currentTarget.value
    setQuery(val);
  };

  const clearQuery = () => {
    setQuery('');
    queryRef.current.value = '';
    queryRef.current.focus();
  }
  
  const displayStyle = query ? {display: 'block'}: {display: 'none'};

  return (
    <SearchBoxWrapper>
      <i className="iconfont icon-back" onClick={() => props.back()}>&#xe655;</i>
      <input ref={queryRef} className="box" placeholder="搜索歌曲、歌手、专辑" onChange={handleChange}/>
      <i className="iconfont icon-delete" onClick={clearQuery} style={displayStyle}>&#xe600;</i>
    </SearchBoxWrapper>
  )
};

export default React.memo(SearchBox);
